import TopButton from '@/components/TopButton';
import Footer from '@/components/layout/Footer';
import MainContentContainer from '@/components/layout/MainContentContainer';
import TopBar from '@/components/layout/TopBar';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { Noto_Sans_Thai } from 'next/font/google';
import Head from 'next/head';

const notosans = Noto_Sans_Thai({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={notosans.className}>
      <Head>
        <title>BOOMTOON - อ่านการ์ตูน BL ออนไลน์ สายวายห้ามพลาด</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconV2.png" />
      </Head>
      <TopBar />
      <MainContentContainer>
        <Component {...pageProps} />
      </MainContentContainer>
      <TopButton />
      <Footer />
    </main>
  );
}
