export const TODAY_CONTENTS = [
  {
    id: 287,
    alias: 'not_heroine',
    title: 'คุณคะ ฉันไม่ใช่นางเอก!',
    isAdult: false,
    isComplete: false,
    orderNo: 1,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/okotowari/1679052068176.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 17029,
    tag: 'อัพทุกเสาร์,แฟนตาซี,สิงร่าง/ข้ามมิติ,แนวยุโรปโบราณ,รักวัยรุ่น,เกิร์ลครัช,นางเอกเจ้าเสน่ห์,นางเอกเก่ง,นางเอกมีปม,นางเอกเฟรนด์ลี่,พระเอกเพอร์เฟ็ค,พระเอกไทป์ลูกหมา,พระเอกคาริสม่าพุ่ง,พลังวิเศษ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'Yehwon, Salaman',
  },
  {
    id: 261,
    alias: 'inthecastle',
    title: 'In the Castle',
    isAdult: false,
    isComplete: false,
    orderNo: 2,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/inthecastle/1679473947610.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/inthecastle/1679473947896.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 137787,
    tag: 'อัพทุกเสาร์,BL,แฟนตาซี,BDSM,สายดาร์ค,ฮาร์ดคอร์,ตลก/คอมเมดี้,เราสองสามคน,เหนือธรรมชาติ,อมนุษย์/ปีศาจ,เมะแข็งแกร่ง,เมะอาวุธลับไซส์บิ๊ก,เมะลูกหมา,เมะเจ้าแผนการ,เมะแซ่บ,เคะน่ารัก,เคะแว่น,เคะซื่อบื้อ,รักต่างเผ่าพันธุ์,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'PPURIN',
  },
  {
    id: 279,
    alias: 'lucifer',
    title: 'คิดถึงนะ ลูซิเฟอร์',
    isAdult: false,
    isComplete: false,
    orderNo: 3,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucifer/1679889392925.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 11444,
    tag: 'อัพทุกเสาร์,BL,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,แอบรัก,รักครั้งแรก,เข้าใจผิด,วงการบันเทิง,เมะเพอร์เฟ็ค,เมะเจ้าเล่ห์,เมะคลั่งรัก,เมะไฮโซ,เมะฮอต,เคะน่ารัก,เคะร่าเริง ,เคะอบอุ่น,เคะใสซื่อ,ไอดอล,ดารา,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'MOSCARETO, OKDONG',
  },
  {
    id: 276,
    alias: 'asura',
    title: 'ปกรณัมรักราชาอสูร',
    isAdult: false,
    isComplete: false,
    orderNo: 4,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/asura/1679052815611.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 44818,
    tag: 'อัพทุกเสาร์,BL,ย้อนยุคสมัยโบราณ,สายดาร์ค,ฮาร์ดคอร์,รักต่างชนชั้น,ดราม่า,เมะแข็งแกร่ง,เมะเลว,เมะคนซึน,เมะเลือดเย็น,เมะคลั่งรัก,เมะสำนึกผิด,เคะน่ารัก,เคะใสซื่อ,เคะอบอุ่น,เคะใจดี,เคะมีปม,OnlyBOOMTOON,รักในวัง',
    updatedAt: 1686934800000,
    creators: 'Black kong',
  },
  {
    id: 273,
    alias: 'revenge',
    title: 'แค้นนี้ต้องรัก',
    isAdult: false,
    isComplete: false,
    orderNo: 5,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110368/1678945282528.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 30450,
    tag: 'อัพทุกเสาร์,BL,แก้แค้น,ย้อนอดีต/เกิดใหม่,คู่รักในบริษัท,มนุษย์เงินเดือน,เมะสำนึกผิด,เมะอบอุ่น,เมะสุภาพ,เมะกล้ามปู,เมะฮอต,เมะเด็กกว่า,เคะมีปม,เคะเจ้าแผนการ,เคะเจ้าเล่ห์,เคะสู้คน,เคะแก่กว่า,เหนือธรรมชาติ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'EOJIN',
  },
  {
    id: 266,
    alias: 'cloud_rain',
    title: 'ลิขิตรักเทพมังกร',
    isAdult: false,
    isComplete: false,
    orderNo: 6,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud_rain/1677818130096.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 24419,
    tag: 'อัพทุกเสาร์,BL,โรแมนติคแฟนตาซี,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,รักต่างเผ่าพันธุ์,แฟนตาซี,รักครั้งแรก,เมะขี้แกล้ง,เมะฮอต,เมะแซ่บ,เมะอาวุธลับไซส์บิ๊ก,เมะคลั่งรัก,เคะขี้อาย,เคะซื่อบื้อ,เคะสวย,เคะใสซื่อ,เคะอบอุ่น,เหนือธรรมชาติ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'MOSCARETO, OKDONG',
  },
  {
    id: 256,
    alias: 'dog_and_wolf',
    title: 'ช่วงเวลาของหมาและหมาป่า',
    isAdult: false,
    isComplete: false,
    orderNo: 7,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dogs_and_wolf/1675338357352.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dogs_and_wolf/1680827761783.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 37386,
    tag: 'อัพทุกเสาร์,BL,ดราม่า,Serious,สายดาร์ค,Omegaverse ,เมะแข็งแกร่ง,เมะเจ้าแผนการ,เมะเจ้าเล่ห์,เมะคนซึน,เคะหน้าหวาน,เคะใสซื่อ,เคะมีปม,เคะไซส์มินิ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'Joy, SolWoo Lee',
  },
  {
    id: 253,
    alias: 'under_shadow',
    title: 'รักในเงาแค้น',
    isAdult: false,
    isComplete: false,
    orderNo: 8,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/reunion_shadow/1678692605814.webp',
        type: 'MAIN_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/reunion_shadow/1685596184321.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 31221,
    tag: 'อัพทุกเสาร์,BL,Omegaverse ,ดราม่า,Serious,เราสองสามคน,แก้แค้น,เมะแข็งแกร่ง,เมะอบอุ่น,เมะสำนึกผิด,เคะมีปม,เคะขี้กลัว,มาเฟีย,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'Ceazer',
  },
  {
    id: 134,
    alias: 'B_position',
    title: 'Bad Position',
    isAdult: false,
    isComplete: false,
    orderNo: 9,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/B_position/1650947394604.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 155595,
    tag: 'อัพทุกเสาร์,BL,วงการบันเทิง,ดารา,เมะเจ้าเล่ห์,เมะเพอร์เฟ็ค,เมะอาวุธลับไซส์บิ๊ก,เมะเจ้าแผนการ,เคะสวย,เคะรักจริง,เคะซื่อบื้อ,เคะขี้แย,ความสัมพันธ์,โรแมนติคคอมเมดี้,OnlyBOOMTOON',
    updatedAt: 1685120400000,
    creators: 'Zudo',
  },
  {
    id: 245,
    alias: 'group_project',
    title: 'โปรเจกต์รักอันตรายกับนายสุดฮอต',
    isAdult: false,
    isComplete: false,
    orderNo: 10,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/group_project/1678272594625.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 8956,
    tag: 'อัพทุกเสาร์,BL,โรแมนติคคอมเมดี้,รักวัยรุ่น,รักในมหาลัย,ตลก/คอมเมดี้,เมะอบอุ่น,เมะเพอร์เฟ็ค,เมะลูกหมา,เคะน่ารัก,เคะขี้อาย,เคะซื่อบื้อ,มหาลัย,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'TT',
  },
  {
    id: 139,
    alias: 'night_of_W',
    title: 'ทะเลรัตติกาล',
    isAdult: false,
    isComplete: false,
    orderNo: 11,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779758810.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 1070096,
    tag: 'อัพทุกเสาร์,BL,Omegaverse ,ฮาร์ดคอร์,เมะแข็งแกร่ง,เมะเจ้าแผนการ,เมะเจ้าเล่ห์,เมะแซ่บ,เมะสำนึกผิด,เคะสู้คน,เคะมีปม,เคะคนตรง,มาเฟีย,OnlyBOOMTOON',
    updatedAt: 1685725200000,
    creators: 'euja',
  },
  {
    id: 52,
    alias: 'BBanana_S',
    title: 'บานาน่า สแกนเดิล',
    isAdult: false,
    isComplete: false,
    orderNo: 12,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/BBanana_S/1666595380908.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 134737,
    tag: 'อัพทุกเสาร์,BL,ดราม่า,เมะสำนึกผิด,เคะแอบรัก,รักในมหาลัย,เพื่อนร่วมบ้าน,รุ่นพี่รุ่นน้อง,เมะอบอุ่น,เมะขี้หวง,รักหวานแหวว,เคะแก่กว่า,เมะหน้าหวาน,มหาลัย,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'DolSHA',
  },
  {
    id: 157,
    alias: 'spinach_fl',
    title: 'Spinach Bouquet',
    isAdult: false,
    isComplete: false,
    orderNo: 13,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/spinach_fl/1675768703750.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 35198,
    tag: 'อัพทุกเสาร์,BL,รักวัยรุ่น,โรแมนติคคอมเมดี้,Feelgood,น่ารัก,เข้าใจผิด,เมะอบอุ่น,เมะคนตรง,เมะเจ้าเล่ห์,เคะมีปม,เคะขี้แย,เคะขี้อาย,เคะไม่โดดเด่น,เพื่อนข้างบ้าน,รุ่นพี่รุ่นน้อง,โรงเรียน,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'TERRA',
  },
  {
    id: 30,
    alias: 'talkto',
    title: 'Talk  to Me',
    isAdult: false,
    isComplete: false,
    orderNo: 15,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/talkto/1630864044662.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/talkto/1664173420096.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 2,
      freetime: false,
    },
    viewCount: 174259,
    tag: 'อัพทุกเสาร์,โรมานซ์,OnlyBOOMTOON,รักในมหาลัย,นางเอกแซ่บ,นางเอกขี้ยั่ว,พระเอกแซ่บ,พระเอกสุภาพ,มหาลัย,ความสัมพันธ์',
    updatedAt: 1686934800000,
    creators: 'อึนบยอล',
  },
  {
    id: 187,
    alias: 'scum',
    title: 'ถิ่นคนเถื่อน',
    isAdult: false,
    isComplete: false,
    orderNo: 16,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570689972.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 427404,
    tag: 'อัพทุกเสาร์,BL,ดราม่า,สายดาร์ค,รักต่างวัย,กลับมาพบกันอีกครั้ง,เมะแข็งแกร่ง,เมะเลือดเย็น,เมะแอบรัก,เมะคลั่งรัก,เมะอาวุธลับไซส์บิ๊ก,เมะเด็กกว่า,เคะกล้ามปู,เคะมีปม,เคะแข็งแกร่ง,เคะคนซึน,มาเฟีย,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'Brothers Without A Tomorrow',
  },
  {
    id: 95,
    alias: 'S_s_B_L',
    title: 'วัยรุ่นวุ่นรัก',
    isAdult: false,
    isComplete: false,
    orderNo: 17,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S_s_B_L/1654764078243.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 46649,
    tag: 'อัพทุกเสาร์,BL,รักวัยรุ่น,โรแมนติคคอมเมดี้,Feelgood,แอบรัก,รักในโรงเรียน,เพื่อนรักรักเพื่อน,เมะเพอร์เฟ็ค,เคะสู้คน,เคะสดใส,โรงเรียน,OnlyBOOMTOON',
    updatedAt: 1668186000000,
    creators: 'JAGAL',
  },
  {
    id: 2,
    alias: 'CEO_and_K',
    title: 'ประธานตัวร้ายกับยัยเลขาคึม',
    isAdult: false,
    isComplete: false,
    orderNo: 18,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/BOOMTOON_COM/co_thumbnail/ceonk/1627035643620.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/BOOMTOON_COM/co_thumbnail/ceonk/1627035643842.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 84181,
    tag: 'โรมานซ์,OnlyBOOMTOON,คู่รักในบริษัท,โรแมนติคคอมเมดี้,แอบรัก,การเติบโต,พระเอกเพอร์เฟ็ค,พระเอกใจดี,นางเอกเฟรนด์ลี่,พระเอกรักจริง,พระเอกคนตรง,โสดตั้งแต่เกิด,ออฟฟิต,เข้าใจผิด,พระเอกรวย,นางเอกเก่ง,เกิร์ลครัช,Feelgood,จบแล้ว',
    updatedAt: 1631552400000,
    creators: 'Limejeongwon, KIRTY',
  },
  {
    id: 108,
    alias: 'su_recipe',
    title: 'สูตรลับฉบับเลิฟ',
    isAdult: false,
    isComplete: false,
    orderNo: 19,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/su_recipe/1648796290608.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 27746,
    tag: 'BL,โรแมนติคคอมเมดี้,แอบรัก,เพื่อนข้างบ้าน,กลับมาพบกันอีกครั้ง,ทำอาหาร,OnlyBOOMTOON,จบแล้ว',
    updatedAt: 1653066000000,
    creators: 'COM',
  },
  {
    id: 158,
    alias: 'Viagra',
    title: 'ไวอากรา Just Friend',
    isAdult: false,
    isComplete: false,
    orderNo: 20,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Viagra/1659400978481.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 65041,
    tag: 'อัพทุกเสาร์,โรมานซ์,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,เพื่อนสมัยเด็ก,เพื่อนรักรักเพื่อน,พระเอกไทป์ลูกหมา,พระเอกใสซื่อ,นางเอกเฟรนด์ลี่,นางเอกแซ่บ,OnlyBOOMTOON,เรื่องสั้น,XX_Vacation',
    updatedAt: 1661014800000,
    creators: 'MOGABI',
  },
  {
    id: 255,
    alias: 'meteor',
    title: 'ลิขิตรักคืนฝนดาวตก',
    isAdult: false,
    isComplete: false,
    orderNo: 21,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shootingST/1677547715515.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 27113,
    tag: 'BL,โรแมนติคคอมเมดี้,กลับมาพบกันอีกครั้ง,วงการบันเทิง,เข้าใจผิด,เมะแข็งแกร่ง,เมะรักจริง,เมะอบอุ่น,เคะกล้ามปู,เคะมีปม,เคะคนซึน,ตากล้อง,ไอดอล,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1677862800000,
    creators: 'Wansik',
  },
];
