export const NEWEST_CONTENTS = [
  {
    id: 298,
    alias: 'placebo',
    title: 'Placebo',
    isAdult: false,
    isComplete: false,
    orderNo: 15,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/placebo/1685511881877.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/placebo/1685511882053.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/placebo/1685511882213.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 4787,
    tag: 'อัพทุกวันศุกร์,BL',
    updatedAt: 1686920400000,
    creators: 'cuke soap',
  },
  {
    id: 305,
    alias: 'weakness',
    title: 'WEAKNESS',
    isAdult: false,
    isComplete: false,
    orderNo: 16,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/her_weakne/1686102561700.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/her_weakne/1686102561920.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/her_weakne/1686102562074.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 2277,
    tag: 'GL,ดราม่า,สายดาร์ค,นางเอกไฮโซ,นางเอกเพอร์เฟ็ค,นางเอกแซ่บ,นางเอกจน,นางเอกร้าย,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1686848400000,
    creators: 'BBTAN',
  },
  {
    id: 296,
    alias: 'secret_diary',
    title: 'บันทึกลับของเลดี้เอลิชา',
    isAdult: false,
    isComplete: false,
    orderNo: 18,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886066.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886213.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886365.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 29808,
    tag: 'อัพทุกวันจันทร์,โรมานซ์,แฟนตาซี,เราสองสามคน,โรแมนติคคอมเมดี้,แนวยุโรปโบราณ,ตลก/คอมเมดี้,สิงร่าง/ข้ามมิติ,นางเอกเจ้าเสน่ห์,นางเอกเพอร์เฟ็ค,นางเอกขี้ยั่ว,นางเอกแซ่บ,OnlyBOOMTOON',
    updatedAt: 1686502800000,
    creators: 'Jangsegu',
  },
  {
    id: 294,
    alias: 'move_into',
    title: 'ให้ผมมาอยู่ด้วยไม่ได้เหรอครับ?',
    isAdult: false,
    isComplete: false,
    orderNo: 19,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660255.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660396.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660678.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 16997,
    tag: 'BL,ออฟฟิต,มนุษย์เงินเดือน,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะเด็กกว่า,เมะคลั่งรัก,เมะแว่น,เคะน่ารัก,เคะใจดี,เคะใสซื่อ,เคะแก่กว่า,เคะซื่อบื้อ,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1686330000000,
    creators: 'Gu Chil',
  },
  {
    id: 292,
    alias: 'fake_romance',
    title: 'Fake Romance',
    isAdult: false,
    isComplete: false,
    orderNo: 20,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110316/1679564779524.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110316/1679564779657.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110316/1679564779808.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 23983,
    tag: 'อัพทุกวันพฤหัส,BL,แอบรัก,ดราม่า,เมะเพอร์เฟ็ค,เมะลูกหมา,เมะแอบรัก,เมะฮอต,เมะเด็กกว่า,เมะมีปม,เมะใสซื่อ,เคะเจ้าเล่ห์,เคะเจ้าแผนการ,เคะแก่กว่า,เคะขี้ยั่ว,เคะแซ่บ,รุ่นพี่รุ่นน้อง,OnlyBOOMTOON',
    updatedAt: 1686762000000,
    creators: 'Tan Geum',
  },
  {
    id: 283,
    alias: 'wave',
    title: 'คลื่นที่ซัดเข้าหาเธอ',
    isAdult: false,
    isComplete: false,
    orderNo: 21,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/oleaje-hacia-ti/1680503290191.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/oleaje-hacia-ti/1680503290354.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/oleaje-hacia-ti/1680503290569.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 42731,
    tag: 'อัพทุกวันอังคาร,BL,Omegaverse ,โรแมนติคคอมเมดี้,เมะคนซึน,เมะคลั่งรัก,เมะกล้ามปู,เมะฮอต,เคะสวย,เคะมีปม,เคะรักจริง,เคะใสซื่อ,Mpreg,เลี้ยงเด็ก,OnlyBOOMTOON',
    updatedAt: 1686589200000,
    creators: 'Cheongyeon',
  },
  {
    id: 293,
    alias: 'retaking',
    title: 'Retaking Romance',
    isAdult: false,
    isComplete: false,
    orderNo: 22,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dozyou/1681445484023.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dozyou/1681445484167.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dozyou/1681445484353.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 14502,
    tag: 'อัพทุกอาทิตย์,BL,โรแมนติคคอมเมดี้,กลับมาพบกันอีกครั้ง,เพื่อนรักรักเพื่อน,เข้าใจผิด,เมะคนซึน,เมะขี้แย,เมะเย็นชา,เมะแอบรัก,เคะร่าเริง ,เคะขี้ยั่ว,เคะแซ่บ,รักในที่ทำงาน,ออฟฟิต,เพื่อนเก่า,เราสองสามคน,OnlyBOOMTOON',
    updatedAt: 1686416400000,
    creators: 'Bareum',
  },
  {
    id: 290,
    alias: 'please_candy',
    title: 'Please, Candy!',
    isAdult: false,
    isComplete: false,
    orderNo: 23,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/please_can/1684395628274.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/please_can/1684395628487.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/please_can/1684395628760.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 40611,
    tag: 'BL,กลับมาพบกันอีกครั้ง,มนุษย์เงินเดือน,เมะเจ้าแผนการ,เมะแอบรัก,เคะแอบรัก,เคะใสซื่อ,ออฟฟิต,รุ่นพี่รุ่นน้อง,รักในที่ทำงาน,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1685638800000,
    creators: 'NOD',
  },
  {
    id: 291,
    alias: 'horizon',
    title: 'สุดทางรักคู่ขนาน',
    isAdult: false,
    isComplete: false,
    orderNo: 24,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654681758.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654681907.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654682125.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 45132,
    tag: 'อัพทุกวันพุธ,BL,เราสองสามคน,ดราม่า,อมนุษย์/ปีศาจ,เมะแซ่บ,เมะใจดี,เมะฮอต,เมะอบอุ่น,เมะสำนึกผิด,เคะน่ารัก,เคะหน้าหวาน,เคะแอบรัก,เคะมีปม,เหนือธรรมชาติ,มหาลัย,OnlyBOOMTOON',
    updatedAt: 1686675600000,
    creators: 'Team S＆S',
  },
  {
    id: 288,
    alias: 'error',
    title: 'นายเด็กใหม่ เขาไม่ชอบผมครับ',
    isAdult: false,
    isComplete: false,
    orderNo: 25,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/error/1677031686191.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/error/1677031686420.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/error/1677031686712.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 14386,
    tag: 'อัพทุกวันจันทร์,BL,โรแมนติคคอมเมดี้,รักวัยรุ่น,ตลก/คอมเมดี้,น่ารัก,Feelgood,แอบรัก,เข้าใจผิด,รักครั้งแรก,เพื่อนรักรักเพื่อน,เมะอบอุ่น,เมะสดใส,เมะขี้แกล้ง,เมะใสซื่อ,เคะขี้อาย,เคะคนซึน,เคะคนตรง,โรงเรียน,OnlyBOOMTOON',
    updatedAt: 1686502800000,
    creators: 'soui',
  },
  {
    id: 287,
    alias: 'not_heroine',
    title: 'คุณคะ ฉันไม่ใช่นางเอก!',
    isAdult: false,
    isComplete: false,
    orderNo: 26,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/okotowari/1679052067819.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/okotowari/1679052068000.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/okotowari/1679052068176.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 17029,
    tag: 'อัพทุกเสาร์,แฟนตาซี,สิงร่าง/ข้ามมิติ,แนวยุโรปโบราณ,รักวัยรุ่น,เกิร์ลครัช,นางเอกเจ้าเสน่ห์,นางเอกเก่ง,นางเอกมีปม,นางเอกเฟรนด์ลี่,พระเอกเพอร์เฟ็ค,พระเอกไทป์ลูกหมา,พระเอกคาริสม่าพุ่ง,พลังวิเศษ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'Yehwon, Salaman',
  },
  {
    id: 286,
    alias: 'cleaning_obsession',
    title: 'รุ่นพี่คลั่งสะอาด',
    isAdult: false,
    isComplete: false,
    orderNo: 27,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/senpai/1684810562203.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/senpai/1684810562403.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/senpai/1684810562613.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 14199,
    tag: 'BL,BDSM,สายดาร์ค,ฮาร์ดคอร์,ดราม่า,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะคลั่งรัก,เมะเด็กกว่า,เมะเลว,เคะไม่ใส่ใจ,เคะหัวแข็ง,เคะมีปม,เคะแก่กว่า,เคะไทป์แมว,ออฟฟิต,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1684947600000,
    creators: 'Grey',
  },
  {
    id: 272,
    alias: 'step-lover',
    title: 'Step-Lover',
    isAdult: false,
    isComplete: false,
    orderNo: 28,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110132/1676883337046.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110132/1676883337258.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110132/1676883337463.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 22393,
    tag: 'อัพทุกวันพุธ,BL,คู่รักในบริษัท,รักในที่ทำงาน,เมะแข็งแกร่ง,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะแซ่บ,เมะสุภาพ,เคะขี้แกล้ง,เคะมีปม,เคะหัวแข็ง,เคะแซ่บ,เจ้านาย,ออฟฟิต,มนุษย์เงินเดือน,OnlyBOOMTOON',
    updatedAt: 1686675600000,
    creators: 'jungwoo',
  },
  {
    id: 289,
    alias: 'lucky_housekeeper',
    title: 'คุณพ่อบ้านสุดลักกี้!',
    isAdult: false,
    isComplete: false,
    orderNo: 29,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucky_housekeeper/1684301666338.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucky_housekeeper/1684301666538.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucky_housekeeper/1684301666776.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 29231,
    tag: 'BL,เมะเพอร์เฟ็ค,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะปากร้าย,เมะฮอต,เมะคลั่งรัก,เคะน่ารัก,เคะแซ่บ,เคะขี้ยั่ว,เคะร่าเริง ,เจ้านาย,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1684688400000,
    creators: 'Orizzim, ZG',
  },
  {
    id: 279,
    alias: 'lucifer',
    title: 'คิดถึงนะ ลูซิเฟอร์',
    isAdult: false,
    isComplete: false,
    orderNo: 30,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucifer/1679889392581.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucifer/1679889392782.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/lucifer/1679889392925.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 11444,
    tag: 'อัพทุกเสาร์,BL,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,แอบรัก,รักครั้งแรก,เข้าใจผิด,วงการบันเทิง,เมะเพอร์เฟ็ค,เมะเจ้าเล่ห์,เมะคลั่งรัก,เมะไฮโซ,เมะฮอต,เคะน่ารัก,เคะร่าเริง ,เคะอบอุ่น,เคะใสซื่อ,ไอดอล,ดารา,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'MOSCARETO, OKDONG',
  },
  {
    id: 278,
    alias: 'anxious_inspector',
    title: 'เสน่ห์รักคุณสารวัตร',
    isAdult: false,
    isComplete: false,
    orderNo: 31,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667511.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667661.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667797.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 94273,
    tag: 'โรมานซ์,รักต่างวัย,กลับมาพบกันอีกครั้ง,พระเอกเซ็กซี่,พระเอกสุภาพ,พระเอกเด็กกว่า,พระเอกรักจริง,พระเอกไทป์ลูกหมา,นางเอกใจดี,นางเอกแก่กว่า,นางเอกคนตรง,นางเอกเก่ง,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1684342800000,
    creators: 'Bulgama',
  },
  {
    id: 285,
    alias: 'turn_back',
    title: 'ขอทวงคืนจองอูคนเดิม!',
    isAdult: false,
    isComplete: false,
    orderNo: 32,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/friendship/1683177738246.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/friendship/1683177738425.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/friendship/1683177738680.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 15007,
    tag: 'BL,กลับมาพบกันอีกครั้ง,เพื่อนรักรักเพื่อน,เมะคนซึน,เมะเจ้าเล่ห์,เมะคลั่งรัก,เมะเจ้าแผนการ,เมะแอบรัก,เคะน่ารัก,เคะใจดี,เคะใสซื่อ,เคะอบอุ่น,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1684170000000,
    creators: 'nuck',
  },
  {
    id: 273,
    alias: 'revenge',
    title: 'แค้นนี้ต้องรัก',
    isAdult: false,
    isComplete: false,
    orderNo: 33,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110368/1678945282252.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110368/1678945282384.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110368/1678945282528.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 30450,
    tag: 'อัพทุกเสาร์,BL,แก้แค้น,ย้อนอดีต/เกิดใหม่,คู่รักในบริษัท,มนุษย์เงินเดือน,เมะสำนึกผิด,เมะอบอุ่น,เมะสุภาพ,เมะกล้ามปู,เมะฮอต,เมะเด็กกว่า,เคะมีปม,เคะเจ้าแผนการ,เคะเจ้าเล่ห์,เคะสู้คน,เคะแก่กว่า,เหนือธรรมชาติ,OnlyBOOMTOON',
    updatedAt: 1686934800000,
    creators: 'EOJIN',
  },
  {
    id: 277,
    alias: 'last_will',
    title: 'เลื่อนวันตายเพื่อคำขอสุดท้าย',
    isAdult: false,
    isComplete: false,
    orderNo: 34,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/last_will/1680162817849.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/last_will/1680162818065.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/last_will/1680162818231.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 16988,
    tag: 'อัพทุกวันพุธ,BL,แฟนตาซี,พลังวิเศษ,รักครั้งแรก,เมะเด็กกว่า,เมะอบอุ่น,เมะแข็งแกร่ง,เมะลูกหมา,เมะคลั่งรัก,เคะหน้าหวาน,เคะมีปม,เคะแก่กว่า,เคะแข็งแกร่ง,เคะเสียสละ,เหนือธรรมชาติ,ต่อสู้,OnlyBOOMTOON',
    updatedAt: 1686675600000,
    creators: 'Sorim, HYEON',
  },
  {
    id: 282,
    alias: 'reflection',
    title: 'ดั่งภาพสะท้อน',
    isAdult: false,
    isComplete: false,
    orderNo: 35,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mirrors/1682654035579.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mirrors/1682654035810.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mirrors/1682654036038.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 10714,
    tag: 'BL,สายดาร์ค,ฮาร์ดคอร์,ดราม่า,ความสัมพันธ์ต้องห้าม,เมะเด็กกว่า,เมะเจ้าแผนการ,เมะเจ้าเล่ห์,เมะคลั่งรัก,เคะมีปม,เคะใสซื่อ,เคะอ่อนแอ,เคะหน้าหวาน,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1683565200000,
    creators: 'Changcheol Kwak',
  },
];
