export const FOR_YOU_CONTENTS = [
  {
    id: 297,
    alias: 'khankhan',
    title: 'ทาสรักของคุน ค่านค่าน',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/khankhan/1683178103442.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/khankhan/1683178103598.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/khankhan/1683178103793.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/khankhan/1683178103978.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/khankhan/1683178104218.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 5229,
    tag: 'อัพทุกอาทิตย์,BL,ย้อนยุคสมัยโบราณ,สิงร่าง/ข้ามมิติ,ตลก/คอมเมดี้,โรแมนติคคอมเมดี้,เมะฮอต,เมะใสซื่อ,เมะลูกหมา,เคะแข็งแกร่ง,เคะไทป์แมว,เคะราชินี,เคะสวย,รักในวัง,ทาส,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: true,
      isIosApp: true,
    },
    updatedAt: 1687021200000,
    creators: 'Cactus Thorn, K.ssal, syunnyun',
  },
  {
    id: 231,
    alias: 'mistress',
    title: 'นายหญิง',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dx_00083/1672203812700.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dx_00083/1672203812886.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dx_00083/1672203813139.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dx_00083/1672203813315.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dx_00083/1672203813532.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 316125,
    tag: 'อัพทุกวันอังคาร,โรมานซ์,ดราม่า,ย้อนยุคสมัยโบราณ,รักต่างชนชั้น,เราสองสามคน,เพื่อนสมัยเด็ก,พระเอกใสซื่อ,พระเอกใจดี,แอบรัก,เจ้านาย,ทาส,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686589200000,
    creators: 'campeace, J B',
  },
  {
    id: 160,
    alias: 'umma_1',
    title: 'สัญญาปีศาจราคะ',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1669768132093.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1669768132281.webp',
        type: 'DETAIL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1675324870624.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1675324870867.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1675324871279.webp',
        type: 'MAIN_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1675324871536.webp',
        type: 'DETAIL_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/umma_1/1675661616410.webp',
        type: 'SQUARE',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 966984,
    tag: 'อัพทุกวันจันทร์,โรมานซ์,โรแมนติคแฟนตาซี,แฟนตาซี,รักต่างเผ่าพันธุ์,เหนือธรรมชาติ,อมนุษย์/ปีศาจ,พระเอกเจ้าเสน่ห์,พระเอกขี้ยั่ว,พระเอกแซ่บ,นางเอกมีปม,นางเอกพิลึก,นางเอกจืดจาง,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686502800000,
    creators: 'KIM MARE',
  },
  {
    id: 63,
    alias: '3rd_end',
    title: 'Third Ending',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/3rd_end/1657531881771.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/3rd_end/1657531882006.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/3rd_end/1657531882186.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/3rd_end/1657531882409.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/3rd_end/1657531882626.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 1160705,
    tag: 'BL,เมะเพอร์เฟ็ค,เมะฮอต,เมะสำนึกผิด,เมะเจ้าแผนการ,เคะน่ารัก,เคะแอบรัก,เคะขี้อาย,เคะใสซื่อ,โรแมนติคคอมเมดี้,แอบรัก,กลับมาพบกันอีกครั้ง,เพื่อนรักรักเพื่อน,รักหวานแหวว,OnlyBOOMTOON,จบแล้ว',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1684342800000,
    creators: 'Chovom',
  },
  {
    id: 112,
    alias: 'shutline',
    title: 'ShutLine',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shutline/1673568746245.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shutline/1673568746588.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shutline/1673568746758.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shutline/1673568746971.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/shutline/1673568747234.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 713016,
    tag: 'อัพทุกสิบวัน,BL,Serious,ดราม่า,ความสัมพันธ์,เมะแข็งแกร่ง,เมะรักจริง,เคะกล้ามปู,เคะเจ้าเล่ห์,เคะแซ่บ,ต่อสู้,มาเฟีย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686416400000,
    creators: 'KYOU',
  },
  {
    id: 252,
    alias: 'zero_gravity',
    title: 'รักไร้แรงโน้มถ่วง',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222497645.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222497778.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222497975.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222498188.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222498438.webp',
        type: 'MAIN_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222498726.webp',
        type: 'DETAIL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222499160.webp',
        type: 'DETAIL_NON_ADULT',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 91237,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคแฟนตาซี,แฟนตาซียุคปัจจุบัน,รักต่างเผ่าพันธุ์,เมะแข็งแกร่ง,เมะเจ้าเล่ห์,เมะหน้าหวาน,เมะแซ่บ,เมะขี้แกล้ง,เมะคลั่งรัก,เคะกล้ามปู,เคะจน,เคะอบอุ่น,เคะไม่โดดเด่น,เหนือธรรมชาติ,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686920400000,
    creators: 'LattePanda',
  },
  {
    id: 259,
    alias: 'help_me_teacher',
    title: 'คุณครับ ช่วยผมด้วย',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Hme_SSNim/1678241964926.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Hme_SSNim/1678241965098.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Hme_SSNim/1678241965351.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Hme_SSNim/1678241965567.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Hme_SSNim/1678241965803.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 296566,
    tag: 'BL,Omegaverse ,เราสองสามคน,3P,แอบรัก,เมะเจ้าเล่ห์,เมะคลั่งรัก,เมะอาวุธลับไซส์บิ๊ก,เมะกล้ามปู,เมะใสซื่อ,เมะแว่น,เมะแซ่บ,เมะเด็กกว่า,เมะแอบรัก,เคะไม่โดดเด่น,เคะกล้ามปู,เคะซื่อบื้อ,OnlyBOOMTOON,เรื่องสั้น',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1678726800000,
    creators: 'surak',
  },
  {
    id: 167,
    alias: 'killer',
    title: 'เมื่อคิลเลอร์ตกหลุมรัก',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/killer/1667779842604.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/killer/1667779842819.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/killer/1667779843000.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/killer/1667779843184.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/killer/1667779843342.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 181767,
    tag: 'อัพทุกอาทิตย์,BL,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,เข้าใจผิด,ปลอมตัว,Feelgood,แอบรัก,เคะซื่อบื้อ,เคะลุง,เคะเลือดเย็น,เคะรักจริง,เคะแอบรัก,เคะแข็งแกร่ง,เมะเพอร์เฟ็ค,เมะใจดี,เมะอบอุ่น,เมะเจ้าเล่ห์,ดารา,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: true,
      isIosApp: true,
    },
    updatedAt: 1687021200000,
    creators: 'eresemo',
  },
  {
    id: 248,
    alias: 'forsythia',
    title: 'เส้นทางรักดอกแคนารี',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/forsythia/1675150861816.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/forsythia/1675150862036.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/forsythia/1675150862161.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/forsythia/1675150862311.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/forsythia/1675150862586.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 77746,
    tag: 'อัพทุกวันพฤหัส,BL,โรแมนติคแฟนตาซี,แฟนตาซี,ตลก/คอมเมดี้,ย้อนยุคสมัยโบราณ,เหนือธรรมชาติ,อมนุษย์/ปีศาจ,เมะลูกหมา,เมะอาวุธลับไซส์บิ๊ก,เมะเด็กกว่า,เมะขี้แกล้ง,เมะสำนึกผิด,เมะคลั่งรัก,เคะมีปม,เคะใจดี,เคะน่ารัก,เคะขี้แย,โรแมนติคคอมเมดี้,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686762000000,
    creators: 'sumrim',
  },
  {
    id: 139,
    alias: 'night_of_W',
    title: 'ทะเลรัตติกาล',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779758187.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779758417.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779758598.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779758810.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/night_of_W/1667779759015.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 1071289,
    tag: 'อัพทุกเสาร์,BL,Omegaverse ,ฮาร์ดคอร์,เมะแข็งแกร่ง,เมะเจ้าแผนการ,เมะเจ้าเล่ห์,เมะแซ่บ,เมะสำนึกผิด,เคะสู้คน,เคะมีปม,เคะคนตรง,มาเฟีย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1685725200000,
    creators: 'euja',
  },
  {
    id: 122,
    alias: 'secret_t',
    title: 'Secret Therapy',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/secret_t/1650947501335.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/secret_t/1650947501660.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/secret_t/1650947501889.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/secret_t/1650947502103.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/secret_t/1650947502328.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 122405,
    tag: 'อัพทุกวันจันทร์,BL,โรแมนติคคอมเมดี้,รักในมหาลัย,รุ่นพี่รุ่นน้อง,เมะขี้แกล้ง,เมะไฮโซ,เมะแซ่บ,เคะจน,เคะหน้าหวาน,เคะใจดี,สตรีมเมอร์,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1672592400000,
    creators: 'Cheongdam',
  },
  {
    id: 94,
    alias: 'speakofthe',
    title: 'Speak of The Devil แอบรักท่านประธานตัวแสบ',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1645417759738.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1645417759905.webp',
        type: 'DETAIL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1675324459912.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1675324460150.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1675324460354.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1675324460510.webp',
        type: 'MAIN_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/speakofthe/1675324460735.webp',
        type: 'DETAIL_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 491686,
    tag: 'อัพทุกวันพฤหัส,BL,รักในที่ทำงาน,แอบรัก,เมะเพอร์เฟ็ค,เมะสำนึกผิด,เมะฮอต,เคะแซ่บ,เคะแอบรัก,เจ้านาย,ออฟฟิต,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1682528400000,
    creators: 'TR, dduckbab',
  },
  {
    id: 291,
    alias: 'horizon',
    title: 'สุดทางรักคู่ขนาน',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654681591.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654681758.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654681907.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654682125.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/_HORIZON/1682654682325.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 45861,
    tag: 'อัพทุกวันพุธ,BL,เราสองสามคน,ดราม่า,อมนุษย์/ปีศาจ,เมะแซ่บ,เมะใจดี,เมะฮอต,เมะอบอุ่น,เมะสำนึกผิด,เคะน่ารัก,เคะหน้าหวาน,เคะแอบรัก,เคะมีปม,เหนือธรรมชาติ,มหาลัย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686675600000,
    creators: 'Team S＆S',
  },
  {
    id: 7,
    alias: 'namsachin',
    title: 'ปิ๊งรักร้าย นายเพื่อนสนิท',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin_th/1627299592756.webp',
        type: 'HORIZONTAL_TYPE_B',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin_th/1627299592947.webp',
        type: 'HORIZONTAL_TYPE_C',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin_th/1627299593167.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin_th/1630299175817.webp',
        type: 'DETAIL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172867944.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868203.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868422.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868646.webp',
        type: 'MAIN_NON_ADULT',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868855.webp',
        type: 'DETAIL_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 518332,
    tag: 'โรมานซ์,โรแมนติคคอมเมดี้,น่ารัก,พระเอกไทป์ลูกหมา,พระเอกใสซื่อ,นางเอกพิลึก,นางเอกขี้ยั่ว,นางเอกคนตรง,OnlyBOOMTOON,เพื่อนรักรักเพื่อน,จบแล้ว',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1678726800000,
    creators: 'Pya pya',
  },
  {
    id: 294,
    alias: 'move_into',
    title: 'ให้ผมมาอยู่ด้วยไม่ได้เหรอครับ?',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660088.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660255.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660396.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660678.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moveinto/1685059660927.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 17443,
    tag: 'BL,ออฟฟิต,มนุษย์เงินเดือน,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะเด็กกว่า,เมะคลั่งรัก,เมะแว่น,เคะน่ารัก,เคะใจดี,เคะใสซื่อ,เคะแก่กว่า,เคะซื่อบื้อ,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686330000000,
    creators: 'Gu Chil',
  },
  {
    id: 192,
    alias: 'smrn_kfr',
    title: 'สมีร์นาแอนด์คาพรี',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/smrn_kfr/1666178272616.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/smrn_kfr/1666178272810.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/smrn_kfr/1666178272959.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/smrn_kfr/1666178273116.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/smrn_kfr/1666178273302.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 736206,
    tag: 'อัพทุกวันอังคาร,BL,โรแมนติคแฟนตาซี,แนวยุโรปโบราณ,Omegaverse ,เหนือธรรมชาติ,อมนุษย์/ปีศาจ,เมะหน้าหวาน,เมะสวย,เมะเด็กกว่า,เมะแข็งแกร่ง,เคะกล้ามปู,เคะเพอร์เฟ็ค,เคะแก่กว่า,Mpreg,เคะราชินี,อัศวิน,พลังวิเศษ,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686589200000,
    creators: 'Brothers Without A Tomorrow',
  },
  {
    id: 187,
    alias: 'scum',
    title: 'ถิ่นคนเถื่อน',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570689361.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570689554.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570689691.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570689972.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/scum/1663570690190.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 429908,
    tag: 'อัพทุกเสาร์,BL,ดราม่า,สายดาร์ค,รักต่างวัย,กลับมาพบกันอีกครั้ง,เมะแข็งแกร่ง,เมะเลือดเย็น,เมะแอบรัก,เมะคลั่งรัก,เมะอาวุธลับไซส์บิ๊ก,เมะเด็กกว่า,เคะกล้ามปู,เคะมีปม,เคะแข็งแกร่ง,เคะคนซึน,มาเฟีย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686934800000,
    creators: 'Brothers Without A Tomorrow',
  },
  {
    id: 76,
    alias: 'pearl_boy',
    title: 'Pearl Boy',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/seashell_boy/1666844768065.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/seashell_boy/1666844768321.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/seashell_boy/1666844768561.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/seashell_boy/1666844768776.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/seashell_boy/1666844769048.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 917715,
    tag: 'อัพทุกวันพุธ,BL,ดราม่า,สายดาร์ค,แฟนตาซี,เมะเจ้าเล่ห์,เมะคลั่งรัก,เมะลูกหมา,เมะฮอต,เมะอบอุ่น,เคะสวย,เคะหน้าหวาน,เคะขี้กลัว,เคะมีปม,เคะใจดี,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686675600000,
    creators: 'Inking',
  },
  {
    id: 151,
    alias: 'mongmong',
    title: 'รักใส ๆ ของนายโฮ่งโฮ่ง',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838154562.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838154738.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838154934.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838155158.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838155370.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 210168,
    tag: 'อัพทุกวันศุกร์,BL,เหนือธรรมชาติ,โรแมนติคแฟนตาซี,เมะลูกหมา,เมะขี้แย,เมะหน้าหวาน,เมะคลั่งรัก,เคะน่ารัก,เคะซื่อบื้อ,เคะสดใส,เพื่อนรักรักเพื่อน,เราสองสามคน,สัตว์,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686848400000,
    creators: ' ongsim',
  },
  {
    id: 225,
    alias: 'dawn_cloud_river',
    title: 'รุ่งอรุณ เมฆา วารี',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dawn_cloud_river/1669941233059.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dawn_cloud_river/1669941233363.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dawn_cloud_river/1669941233470.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dawn_cloud_river/1669941233639.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dawn_cloud_river/1669941233818.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 420980,
    tag: 'อัพทุกวันจันทร์,BL,โรแมนติคแฟนตาซี,เหนือธรรมชาติ,อมนุษย์/ปีศาจ,กลับมาพบกันอีกครั้ง,เมะแข็งแกร่ง,เมะคลั่งรัก,เมะอาวุธลับไซส์บิ๊ก,เมะคนซึน,เมะลูกหมา,เมะขี้แย,เคะเพอร์เฟ็ค,เคะแข็งแกร่ง,เคะสุภาพ,เคะอบอุ่น,พลังวิเศษ,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1685898000000,
    creators: 'Ma jeung ji',
  },
  {
    id: 58,
    alias: 'hate_love',
    title: 'รอยรักในรอยชัง',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hate_love/1636522651808.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hate_love/1636522652010.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hate_love/1636522652196.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hate_love/1636522652340.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hate_love/1636522652606.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 166223,
    tag: 'BL,แฟนตาซี,Serious,แนวยุโรปโบราณ,รักในโรงเรียน,อมนุษย์/ปีศาจ,เราสองสามคน,แอบรัก,ต่อสู้,รุ่นพี่รุ่นน้อง,เมะลูกหมา,เมะแอบรัก,เมะใสซื่อ,เมะเด็กกว่า,เคะมีปม,เคะเจ้าแผนการ,เคะแซ่บ,OnlyBOOMTOON,เรื่องสั้น',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1640710800000,
    creators: 'Buzzi',
  },
  {
    id: 296,
    alias: 'secret_diary',
    title: 'บันทึกลับของเลดี้เอลิชา',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606885818.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886066.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886213.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886365.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/1000606/1683606886553.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 31972,
    tag: 'อัพทุกวันจันทร์,โรมานซ์,แฟนตาซี,เราสองสามคน,โรแมนติคคอมเมดี้,แนวยุโรปโบราณ,ตลก/คอมเมดี้,สิงร่าง/ข้ามมิติ,นางเอกเจ้าเสน่ห์,นางเอกเพอร์เฟ็ค,นางเอกขี้ยั่ว,นางเอกแซ่บ,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686502800000,
    creators: 'Jangsegu',
  },
  {
    id: 226,
    alias: 'not_friend',
    title: 'แค่เพื่อนไม่พอ',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/blurredlines/1672914322032.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/blurredlines/1672914322260.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/blurredlines/1672914322426.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/blurredlines/1672914322593.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/blurredlines/1672914322851.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 508769,
    tag: 'อัพทุกวันพุธ,โรมานซ์,รักในมหาลัย,เพื่อนรักรักเพื่อน,รักครั้งแรก,แอบรัก,พระเอกใสซื่อ,พระเอกเจี๋ยมเจี้ยม,นางเอกแซ่บ,นางเอกขี้ยั่ว,นางเอกเจ้าเสน่ห์,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686675600000,
    creators: 'baepero, saeltto',
  },
  {
    id: 249,
    alias: 'egocentric',
    title: 'รักนี้หมุนรอบตัวเอง : Egocentric Way of Thinking',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/egocentric/1675758274055.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/egocentric/1675758274298.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/egocentric/1675758274522.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/egocentric/1675758274729.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/egocentric/1675758274959.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 74018,
    tag: 'อัพทุกสิบวัน,BL,โรแมนติคคอมเมดี้,น่ารัก,แอบรัก,มนุษย์เงินเดือน,ออฟฟิต,เมะแข็งแกร่ง,เมะเจ้าแผนการ,เมะเพอร์เฟ็ค,เมะขี้แกล้ง,เคะไม่โดดเด่น,เคะแอบรัก,เคะซื่อบื้อ,เจ้านาย,รักในที่ทำงาน,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686416400000,
    creators: 'wonmic, JeonMin',
  },
  {
    id: 278,
    alias: 'anxious_inspector',
    title: 'เสน่ห์รักคุณสารวัตร',
    isAdult: false,
    isComplete: true,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667349.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667511.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667661.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667797.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/anxious_inspector/1680771667978.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 95307,
    tag: 'โรมานซ์,รักต่างวัย,กลับมาพบกันอีกครั้ง,พระเอกเซ็กซี่,พระเอกสุภาพ,พระเอกเด็กกว่า,พระเอกรักจริง,พระเอกไทป์ลูกหมา,นางเอกใจดี,นางเอกแก่กว่า,นางเอกคนตรง,นางเอกเก่ง,OnlyBOOMTOON,เรื่องสั้น',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1684342800000,
    creators: 'Bulgama',
  },
  {
    id: 177,
    alias: 'badthinking',
    title: 'Bad Thinking Diary',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/badthinking/1662105876681.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/badthinking/1662105877123.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/badthinking/1662105877314.webp',
        type: 'DETAIL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/badthinking/1675323258232.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/badthinking/1675323258459.webp',
        type: 'SQUARE',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 1322532,
    tag: 'อัพทุกวันอังคาร,GL,เพื่อนรักรักเพื่อน,เข้าใจผิด,แอบรัก,รักวัยรุ่น,รักในมหาลัย,นางเอกเฟรนด์ลี่,นางเอกใสซื่อ,นางเอกขี้หวง,นางเอกแซ่บ,นางเอกเจ้าเสน่ห์,มหาลัย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686589200000,
    creators: 'Rangrari, Hodan',
  },
  {
    id: 27,
    alias: 'illusion',
    title: 'เพราะรักคือภาพลวงตา Love is an Illusion!',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/illusion/1631256550270.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/illusion/1631256550470.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/illusion/1631256550639.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/illusion/1631256550828.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/illusion/1631256550986.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 1148297,
    tag: 'อัพทุกสิบวัน,BL,OnlyBOOMTOON,Omegaverse ,เมะเพอร์เฟ็ค,เมะไฮโซ,เคะหัวแข็ง,เคะซื่อบื้อ,Mpreg,เมะคนซึน,น่ารัก,เลี้ยงเด็ก',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686416400000,
    creators: 'Fargo',
  },
  {
    id: 89,
    alias: 'cloud',
    title: 'Cloud',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568856404.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568856693.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568856862.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568857130.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568857307.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 232262,
    tag: 'อัพทุกวันศุกร์,BL,รักวัยรุ่น,รักในโรงเรียน,แอบรัก,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เคะแว่น,ตากล้อง,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: true,
      isIosApp: true,
    },
    updatedAt: 1686848400000,
    creators: 'kimpas',
  },
  {
    id: 200,
    alias: 'duchess_debauchery',
    title: 'Duchess Debauchery',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dbd_00052/1675327239524.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dbd_00052/1675327239751.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dbd_00052/1675327239900.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dbd_00052/1675327240117.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/dbd_00052/1675327240318.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 204515,
    tag: 'อัพทุกวันพฤหัส,โรมานซ์,แนวยุโรปโบราณ,รักในวัง,พระเอกเย็นชา,พระเอกไม่ใส่ใจ,พระเอกเพอร์เฟ็ค,พระเอกแซ่บ,นางเอกใจดี,นางเอกมีปม,นางเอกขี้ยั่ว,นางเอกแซ่บ,เข้าใจผิด,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1686762000000,
    creators: 'GOYO, Jusang',
  },
  {
    id: 233,
    alias: 'no_moral',
    title: 'No Moral',
    isAdult: false,
    isComplete: false,
    orderNo: 0,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110234/1674021255938.webp',
        type: 'HORIZONTAL_TYPE_A',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110234/1674021256135.webp',
        type: 'VERTICAL',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110234/1674021256309.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110234/1674021256423.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110234/1674021256620.webp',
        type: 'DETAIL',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 34060,
    tag: 'อัพทุกอาทิตย์,BL,กลับมาพบกันอีกครั้ง,เมะเจ้าเล่ห์,เมะแข็งแกร่ง,เมะเพอร์เฟ็ค,เมะปากร้าย,เมะเย็นชา,เมะคนซึน,เมะคนตรง,เคะเสียสละ,เคะใจดี,เคะใสซื่อ,เคะเด็กกว่า,เคะอบอุ่น,ออฟฟิต,รักในที่ทำงาน,เจ้านาย,OnlyBOOMTOON',
    devices: {
      isWeb: true,
      isAndPlay: false,
      isIosApp: false,
    },
    updatedAt: 1687021200000,
    creators: 'TEHANU, SHAMPOO',
  },
];
