export const WEEKLY_CONTENTS = [
  {
    id: 89,
    alias: 'cloud',
    title: 'Cloud',
    isAdult: false,
    isComplete: false,
    orderNo: 3,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568856862.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/cloud/1673568857130.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 231125,
    tag: 'อัพทุกวันศุกร์,BL,รักวัยรุ่น,รักในโรงเรียน,แอบรัก,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เคะแว่น,ตากล้อง,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'kimpas',
  },
  {
    id: 270,
    alias: 'netkama',
    title: 'Netkama Punch!!!',
    isAdult: false,
    isComplete: false,
    orderNo: 4,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/netkama/1678768295596.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/netkama/1678768295755.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 67713,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,เข้าใจผิด,รักหวานแหวว,เมะคลั่งรัก,เมะแข็งแกร่ง,เมะขี้แกล้ง,เมะคนซึน,เคะลุง,เคะมีปม,เคะเจ้าแผนการ,เคะแก่กว่า,เคะน่ารัก,เกม,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'CHIMA, gongben, bongyee',
  },
  {
    id: 151,
    alias: 'mongmong',
    title: 'รักใส ๆ ของนายโฮ่งโฮ่ง',
    isAdult: false,
    isComplete: false,
    orderNo: 5,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838154934.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/mongmong/1684838155158.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 207660,
    tag: 'อัพทุกวันศุกร์,BL,เหนือธรรมชาติ,โรแมนติคแฟนตาซี,เมะลูกหมา,เมะขี้แย,เมะหน้าหวาน,เมะคลั่งรัก,เคะน่ารัก,เคะซื่อบื้อ,เคะสดใส,เพื่อนรักรักเพื่อน,เราสองสามคน,สัตว์,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: ' ongsim',
  },
  {
    id: 133,
    alias: 'avle',
    title: 'AVLE',
    isAdult: false,
    isComplete: false,
    orderNo: 6,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/A_vle/1652230050439.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/A_vle/1652230050628.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 248033,
    tag: 'อัพทุกวันศุกร์,BL,สายดาร์ค,เราสองสามคน,เมะเลว,เมะเจ้าเล่ห์,เมะอาวุธลับไซส์บิ๊ก,เมะกล้ามปู,เมะเจ้าแผนการ,เมะสุภาพ,เมะอบอุ่น,เคะแอบรัก,เคะมีปม,เคะขี้ยั่ว,เคะแซ่บ,แข่งขัน,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'Rangni, GOMDORI',
  },
  {
    id: 252,
    alias: 'zero_gravity',
    title: 'รักไร้แรงโน้มถ่วง',
    isAdult: false,
    isComplete: false,
    orderNo: 7,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222497975.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222498188.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/zero_gravity/1677222498438.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 88942,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคแฟนตาซี,แฟนตาซียุคปัจจุบัน,รักต่างเผ่าพันธุ์,เมะแข็งแกร่ง,เมะเจ้าเล่ห์,เมะหน้าหวาน,เมะแซ่บ,เมะขี้แกล้ง,เมะคลั่งรัก,เคะกล้ามปู,เคะจน,เคะอบอุ่น,เคะไม่โดดเด่น,เหนือธรรมชาติ,OnlyBOOMTOON',
    updatedAt: 1686315600000,
    creators: 'LattePanda',
  },
  {
    id: 260,
    alias: 'woof_wolf',
    title: 'Woof Wolf',
    isAdult: false,
    isComplete: false,
    orderNo: 8,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110056/1675338543895.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/bt_1110056/1675338544088.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 30029,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคแฟนตาซี,แฟนตาซี,รักวัยรุ่น,รักในมหาลัย,แอบรัก,สัตว์,เมะลูกหมา,เมะฮอต,เมะใสซื่อ,เคะแว่น,เคะขี้แกล้ง,เคะแซ่บ,เคะขี้ยั่ว,เหนือธรรมชาติ,มหาลัย,รักต่างเผ่าพันธุ์,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'Magoo',
  },
  {
    id: 61,
    alias: 'moneyromance',
    title: 'Love for Sale',
    isAdult: false,
    isComplete: false,
    orderNo: 9,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moneyromance/1660698947901.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moneyromance/1681460064097.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/moneyromance/1681460064295.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 211859,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคคอมเมดี้,รักต่างวัย,ดราม่า,เคะจน,เคะกล้ามปู,เคะคนซึน,เคะขี้แย,เคะเด็กกว่า,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะแก่กว่า,เมะไฮโซ,เมะพูดเพราะ,เมะอบอุ่น,เมะสุภาพ,เมะแซ่บ,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'Dal HyeonJi',
  },
  {
    id: 215,
    alias: 'wait_for_you',
    title: 'รอเธอหันมา I’ll be here for you',
    isAdult: false,
    isComplete: false,
    orderNo: 10,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/wait_for_you/1678424688226.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/wait_for_you/1678424688426.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/wait_for_you/1678424688589.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 37303,
    tag: 'อัพทุกวันศุกร์,BL,ดราม่า,กลับมาพบกันอีกครั้ง,แอบรัก,เมะหน้าหวาน,เมะสุภาพ,เมะเย็นชา,เมะขี้แย,เมะมีปม,เคะหน้าหวาน,เคะแอบรัก,เคะคนตรง,เคะรักจริง,เคะมีปม,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'Lee hyeon-sook',
  },
  {
    id: 254,
    alias: 'handicraft',
    title: 'โรงรัญจวนสวาท',
    isAdult: false,
    isComplete: false,
    orderNo: 11,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/handicraft/1675338735863.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/handicraft/1675338736093.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 106992,
    tag: 'อัพทุกวันศุกร์,BL,ย้อนยุคสมัยโบราณ,สายดาร์ค,ฮาร์ดคอร์,BDSM,เมะอาวุธลับไซส์บิ๊ก,เมะมีปม,เมะเย็นชา,เมะผมยาว,เมะแซ่บ,เคะขี้ยั่ว,เคะกล้ามปู,เคะเจ้าแผนการ,เคะไฮโซ,เคะคนตรง,โชซอน,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'songmi',
  },
  {
    id: 224,
    alias: 'punkdunkfunk',
    title: 'PUNK DUNK FUNK เสียงเปียโนนำทางใจ',
    isAdult: false,
    isComplete: false,
    orderNo: 12,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/punkdunkfunk/1669199711038.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/punkdunkfunk/1669199711205.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: true,
      up: true,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 61606,
    tag: 'อัพทุกวันศุกร์,BL,รักวัยรุ่น,โรแมนติคคอมเมดี้,กลับมาพบกันอีกครั้ง,เมะเจ้าเล่ห์,เมะเจ้าแผนการ,เมะคลั่งรัก,เมะฮอต,เคะน่ารัก,เคะซื่อบื้อ,เคะใสซื่อ,เคะแก่กว่า,OnlyBOOMTOON',
    updatedAt: 1686848400000,
    creators: 'JANGMA',
  },
  {
    id: 98,
    alias: 'LUCKY_para',
    title: 'Lucky Paradise',
    isAdult: false,
    isComplete: false,
    orderNo: 13,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/LUCKY_para/1645526345786.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/LUCKY_para/1676012303415.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/LUCKY_para/1676012303600.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 2,
      freetime: false,
    },
    viewCount: 172759,
    tag: 'BL,รักในมหาลัย,รุ่นพี่รุ่นน้อง,เมะลูกหมา,เคะกล้ามปู,เมะเด็กกว่า,เคะน่ารัก,เมะขี้แย,เราสองสามคน,ตลก/คอมเมดี้,OnlyBOOMTOON',
    updatedAt: 1686243600000,
    creators: 'Kangneuk',
  },
  {
    id: 69,
    alias: 'viewfinder',
    title: 'ViewFinder',
    isAdult: false,
    isComplete: false,
    orderNo: 14,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/viewfinder/1661254372856.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/viewfinder/1661254373051.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 139196,
    tag: 'BL,เมะเด็กกว่า,เมะขี้หวง,เคะเจ้าเล่ห์,เคะเจ้าแผนการ,เคะหัวแข็ง,ตากล้อง,รุ่นพี่รุ่นน้อง,โรแมนติคคอมเมดี้,รักในมหาลัย,แอบรัก,OnlyBOOMTOON',
    updatedAt: 1686243600000,
    creators: 'EYZI',
  },
  {
    id: 78,
    alias: '2c_hs',
    title: 'ลีฮีซู ห้อง 2',
    isAdult: false,
    isComplete: false,
    orderNo: 15,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/2c_hs/1662434115643.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/2c_hs/1662434115822.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 75495,
    tag: 'อัพทุกวันศุกร์,BL,โรแมนติคคอมเมดี้,รักวัยรุ่น,น่ารัก,Feelgood,แอบรัก,รักในโรงเรียน,เราสองสามคน,เพื่อนรักรักเพื่อน,เคะน่ารัก,เคะไม่โดดเด่น,เคะสดใส,OnlyBOOMTOON',
    updatedAt: 1683824400000,
    creators: 'Lily',
  },
  {
    id: 119,
    alias: 'defineD_R',
    title: 'Define The Relationship ปักหัวใจไว้ที่เธอ',
    isAdult: false,
    isComplete: false,
    orderNo: 16,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/defineD_R/1661520207690.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/defineD_R/1661520207844.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 269052,
    tag: 'อัพทุกวันศุกร์,BL,Omegaverse ,เมะอบอุ่น,เมะแก่กว่า,เมะใจดี,เคะเพอร์เฟ็ค,เคะมีปม,กลับมาพบกันอีกครั้ง,OnlyBOOMTOON',
    updatedAt: 1677171600000,
    creators: 'Flona, CHADA',
  },
  {
    id: 70,
    alias: 'liveta',
    title: 'Liveta',
    isAdult: false,
    isComplete: false,
    orderNo: 17,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/liveta/1660017115166.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/liveta/1660017115356.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: true,
      up: false,
      completed: false,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 354159,
    tag: 'อัพทุกวันศุกร์,BL,Serious,ดราม่า,สายดาร์ค,เมะอาวุธลับไซส์บิ๊ก,เมะลูกหมา,เมะยากจน,เคะเลือดเย็น,เคะเจ้าแผนการ,เคะแซ่บ,เคะแข็งแกร่ง,มาเฟีย,ต่อสู้,เคะราชินี,OnlyBOOMTOON',
    updatedAt: 1667494800000,
    creators: 'Muzi',
  },
  {
    id: 25,
    alias: 'at_the_end',
    title: 'At the End of the Road',
    isAdult: false,
    isComplete: false,
    orderNo: 18,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/at_the_end/1631169694702.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/at_the_end/1631169694846.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/at_the_end/1631169694979.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 4,
      freetime: false,
    },
    viewCount: 245631,
    tag: 'BL,กลับมาพบกันอีกครั้ง,เพื่อนสมัยเด็ก,รักในโรงเรียน,เคะสู้คน,โรแมนติคแฟนตาซี,OnlyBOOMTOON,จบแล้ว,ย้อนอดีต/เกิดใหม่',
    updatedAt: 1631552400000,
    creators: 'Haribo',
  },
  {
    id: 107,
    alias: 'J_Haejin_L',
    title: 'รักแรกของชองแฮจิน',
    isAdult: false,
    isComplete: false,
    orderNo: 19,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/J_Haejin_L/1648796077489.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/J_Haejin_L/1648796077665.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 13,
      freetime: false,
    },
    viewCount: 10558,
    tag: 'โรมานซ์,โรแมนติคแฟนตาซี,น่ารัก,รักครั้งแรก,Feelgood,จบแล้ว',
    updatedAt: 1652979600000,
    creators: 'HONGHYE',
  },
  {
    id: 247,
    alias: 'backlight',
    title: 'ซ่อนรักอำมหิต',
    isAdult: false,
    isComplete: false,
    orderNo: 20,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/backlight/1676882824978.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/backlight/1676882825162.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 11130,
    tag: 'GL,ดราม่า,Serious,แนวยุโรปโบราณ,สายดาร์ค,ทั้งรักทั้งเกลียด,นางเอกร้าย,นางเอกเย็นชา,นางเอกเก่ง,นางเอกใจดี,นางเอกหนี,นางเอกมีปม,นางเอกใสซื่อ,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1677171600000,
    creators: 'mukxxi, PABANE',
  },
  {
    id: 244,
    alias: 'unpleasant',
    title: 'เล่ห์ร้ายนายอัลฟ่า',
    isAdult: false,
    isComplete: false,
    orderNo: 21,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/unpleasant/1675338428382.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/unpleasant/1675915996105.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/unpleasant/1675915996335.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 43117,
    tag: 'BL,Omegaverse ,ดราม่า,สายดาร์ค,ฮาร์ดคอร์,Serious,เมะมีปม,เมะจืดจาง,เคะกล้ามปู,เคะแข็งแกร่ง,รักในมหาลัย,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1675962000000,
    creators: 'SS',
  },
  {
    id: 238,
    alias: 'S2recycle',
    title: 'รักแล้ว รักซ้ำ นำกลับมารักใหม่',
    isAdult: false,
    isComplete: false,
    orderNo: 22,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S2recycle/1674785661203.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S2recycle/1674785661454.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 10855,
    tag: 'GL,โรแมนติคคอมเมดี้,BDSM,นางเอกแซ่บ,นางเอกไม่ใส่ใจ,นางเอกพิลึก,นางเอกรักจริง,ทาสรักยัยตัวร้าย,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1675357200000,
    creators: 'HYUK',
  },
  {
    id: 236,
    alias: 'romantic_letter',
    title: 'จดหมายรักลุ้นเลิฟ',
    isAdult: false,
    isComplete: false,
    orderNo: 23,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/romanticLT/1674623675436.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/romanticLT/1674623675548.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 11461,
    tag: 'BL,โรแมนติคคอมเมดี้,แอบรัก,ตลก/คอมเมดี้,น่ารัก,เมะขี้แย,เมะลูกหมา,เมะเด็กกว่า,เมะขี้กลัว,เมะแอบรัก,เคะหน้าหวาน,เคะแก่กว่า,เคะอบอุ่น,เคะขี้ยั่ว,เคะแซ่บ,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1674838800000,
    creators: 'eolcho',
  },
  {
    id: 201,
    alias: 'flower_blooming',
    title: 'เมื่อดอกไม้บาน',
    isAdult: false,
    isComplete: false,
    orderNo: 24,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/G_S_SN_JS/1667802386725.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/G_S_SN_JS/1667802386922.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 18477,
    tag: 'BL,ย้อนยุคสมัยโบราณ,ดราม่า,ปลอมตัว,เมะอบอุ่น,เมะสุภาพ,เมะเพอร์เฟ็ค,เมะใจดี,เคะเจ้าเล่ห์,เคะเจ้าแผนการ,เคะคนซึน,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1669482000000,
    creators: 'Junah',
  },
  {
    id: 197,
    alias: 'inthehotel',
    title: 'In the hotel, On the bed',
    isAdult: false,
    isComplete: false,
    orderNo: 25,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/inthehotel/1666930395830.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/inthehotel/1666930396059.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 19134,
    tag: 'โรมานซ์,Serious,สายดาร์ค,พระเอกเย็นชา,พระเอกไม่ใส่ใจ,พระเอกเจ้าเสน่ห์,นางเอกเฟรนด์ลี่,นางเอกแซ่บ,นางเอกรักจริง,ทาสรักยัยตัวร้าย,แอบรัก,OnlyBOOMTOON,เรื่องสั้น,Christmas',
    updatedAt: 1671555600000,
    creators: 'RAKO',
  },
  {
    id: 196,
    alias: 'star_nim',
    title: 'วุ่นนักรักสลับร่าง',
    isAdult: false,
    isComplete: false,
    orderNo: 26,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/star_nim/1666682864319.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/star_nim/1666682864466.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 53694,
    tag: 'BL,โรแมนติคแฟนตาซี,โรแมนติคคอมเมดี้,ตลก/คอมเมดี้,สิงร่าง/ข้ามมิติ,เราสองสามคน,3P,เคะราชินี,เคะขี้แกล้ง,เคะแซ่บ,เคะขี้ยั่ว,เมะเย็นชา,เมะเพอร์เฟ็ค,เมะลูกหมา,เมะใสซื่อ,เมะแอบรัก,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1668272400000,
    creators: 'JET',
  },
  {
    id: 189,
    alias: 'safarigame',
    title: 'SAFARI GAME',
    isAdult: false,
    isComplete: false,
    orderNo: 27,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/safarigame/1665124808929.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/safarigame/1675065307372.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/safarigame/1675065307524.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 88936,
    tag: 'BL,โรแมนติคแฟนตาซี,อมนุษย์/ปีศาจ,รักต่างเผ่าพันธุ์,เมะลูกหมา,เมะใจดี,เมะอาวุธลับไซส์บิ๊ก,เมะฮอต,เมะเพอร์เฟ็ค,เคะกล้ามปู,เคะใสซื่อ,เคะน่ารัก,เคะขี้อาย,สัตว์,ตากล้อง,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1667235600000,
    creators: 'Hyeol-Aek',
  },
  {
    id: 173,
    alias: 'whichone',
    title: 'แบบไหนถึงใช่รัก?',
    isAdult: false,
    isComplete: false,
    orderNo: 28,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/whichone/1662106016289.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/whichone/1662106016485.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/whichone/1662106016667.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 83445,
    tag: 'โรมานซ์,BL,BDSM,ข้ามเพศ,โรแมนติคแฟนตาซี,คู่รักในบริษัท,ออฟฟิต,พระเอกเย็นชา,พระเอกใสซื่อ,นางเอกแซ่บ,นางเอกขี้ยั่ว,เมะเจ้าเล่ห์,เมะขี้แกล้ง,เข้าใจผิด,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1663779600000,
    creators: 'TEAM magic body',
  },
  {
    id: 165,
    alias: 'Clerk_K_S',
    title: 'ความลับของพนักงาน K',
    isAdult: false,
    isComplete: false,
    orderNo: 29,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Clerk_K_S/1671161725193.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/Clerk_K_S/1671161725335.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 3,
      freetime: false,
    },
    viewCount: 271268,
    tag: 'BL,โรแมนติคแฟนตาซี,โรแมนติคคอมเมดี้,แวมไพร์,เมะแข็งแกร่ง,เมะแซ่บ,เมะเจ้าแผนการ,เคะน่ารัก,เคะหน้าหวาน,เคะสวย,เคะอ่อนแอ,รักในที่ทำงาน,เจ้านาย,ออฟฟิต,OnlyBOOMTOON,จบแล้ว',
    updatedAt: 1664470800000,
    creators: 'MORAK',
  },
  {
    id: 154,
    alias: 'My_littleP',
    title: 'My Little Passenger',
    isAdult: false,
    isComplete: false,
    orderNo: 30,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/My_littleP/1658817388041.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/My_littleP/1675071386828.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/My_littleP/1675071387076.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 0,
      freetime: false,
    },
    viewCount: 296318,
    tag: 'BL,โรแมนติคคอมเมดี้,เมะใสซื่อ,เมะกล้ามปู,เมะอาวุธลับไซส์บิ๊ก,เมะลูกหมา,เคะแซ่บ,เคะขี้ยั่ว,เคะขี้แกล้ง,เคะสวย,เคะหน้าหวาน,OnlyBOOMTOON,เรื่องสั้น,XX_Vacation',
    updatedAt: 1659286800000,
    creators: 'PPURIN',
  },
  {
    id: 138,
    alias: 'daehyun_w',
    title: 'แดฮยอนซักรีด ~รับรีดทุกสิ่งอย่าง~',
    isAdult: false,
    isComplete: false,
    orderNo: 31,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/daehyun_w/1655106057521.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/daehyun_w/1655106057684.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 269162,
    tag: 'BL,ฮาร์ดคอร์,เมะเจ้าเล่ห์,เมะแซ่บ,เมะฮอต,เมะเด็กกว่า,เมะอาวุธลับไซส์บิ๊ก,เมะปากร้าย,เคะไม่โดดเด่น,เคะซื่อบื้อ,เคะแอบรัก,เคะขี้อาย,เคะน่ารัก,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1655226000000,
    creators: 'JEA',
  },
  {
    id: 118,
    alias: 'hategirl',
    title: 'The girl I hated เกลียดดีนัก รักซะเลย',
    isAdult: false,
    isComplete: false,
    orderNo: 32,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hategirl/1663894455868.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/hategirl/1663894456074.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 49398,
    tag: 'GL,โรแมนติคคอมเมดี้,มนุษย์เงินเดือน,ออฟฟิต,คู่แข่ง,รักในที่ทำงาน,เจ้านาย,น่ารัก,เกิร์ลครัช,OnlyBOOMTOON,เรื่องสั้น',
    updatedAt: 1653757200000,
    creators: 'ownte',
  },
  {
    id: 7,
    alias: 'namsachin',
    title: 'ปิ๊งรักร้าย นายเพื่อนสนิท',
    isAdult: false,
    isComplete: false,
    orderNo: 33,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin_th/1627299593167.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868422.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/namsachin/1664172868646.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 517765,
    tag: 'โรมานซ์,โรแมนติคคอมเมดี้,น่ารัก,พระเอกไทป์ลูกหมา,พระเอกใสซื่อ,นางเอกพิลึก,นางเอกขี้ยั่ว,นางเอกคนตรง,OnlyBOOMTOON,เพื่อนรักรักเพื่อน,จบแล้ว',
    updatedAt: 1678726800000,
    creators: 'Pya pya',
  },
  {
    id: 96,
    alias: '45seconds',
    title: '45 วินาที',
    isAdult: false,
    isComplete: false,
    orderNo: 34,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/45seconds/1646658815468.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/45seconds/1646658815659.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 15329,
    tag: 'GL,โรแมนติคคอมเมดี้,น่ารัก,Feelgood,แอบรัก,รักวัยรุ่น,รักในโรงเรียน,เพื่อนรักรักเพื่อน,กลับมาพบกันอีกครั้ง,รักในมหาลัย,เรื่องสั้น,OnlyBOOMTOON',
    updatedAt: 1650128400000,
    creators: 'TEAM NAMYOON',
  },
  {
    id: 46,
    alias: 'BnS2',
    title: 'Blood and Love ขอรักรุ่นพี่แวมไพร์',
    isAdult: false,
    isComplete: false,
    orderNo: 36,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/BnS2/1649923138772.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/BnS2/1649923138964.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 219004,
    tag: 'BL,น่ารัก,โรแมนติคแฟนตาซี,โรแมนติคคอมเมดี้,รุ่นพี่รุ่นน้อง,เมะสวย,เมะเย็นชา,เคะสดใส,เคะคนตรง,เมะสุภาพ,เมะฮอต,เคะน่ารัก,เคะแอบรัก,เคะอบอุ่น,มหาลัย,รักในมหาลัย,แวมไพร์,OnlyBOOMTOON,แอบรัก,จบแล้ว',
    updatedAt: 1678899600000,
    creators: 'Haesun',
  },
  {
    id: 35,
    alias: 'iS2Pyeha',
    title: 'His Majesty is Mine',
    isAdult: false,
    isComplete: false,
    orderNo: 38,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/iS2Pyeha/1646031452594.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/iS2Pyeha/1664173076638.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/iS2Pyeha/1664173076840.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 712868,
    tag: 'โรมานซ์,โรแมนติคแฟนตาซี,สิงร่าง/ข้ามมิติ,รักต่างชนชั้น,พระเอกเย็นชา,พระเอกเซ็กซี่,พระเอกคาริสม่าพุ่ง,นางเอกแซ่บ,นางเอกขี้ยั่ว,นางเอกเจ้าชู้,นางเอกเจ้าเสน่ห์,นางเอกเฟรนด์ลี่,OnlyBOOMTOON,รักในวัง,จบแล้ว',
    updatedAt: 1657213200000,
    creators: 'DoYeon, ARA',
  },
  {
    id: 23,
    alias: 'S2_plan',
    title: 'แอบกั๊กรักทดลอง',
    isAdult: false,
    isComplete: false,
    orderNo: 39,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S2_plan/1631167740431.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S2_plan/1631167740706.webp',
        type: 'MAIN',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/S2_plan/1631167740959.webp',
        type: 'MAIN_NON_ADULT',
      },
    ],
    badge: {
      newest: false,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 440955,
    tag: 'BL,OnlyBOOMTOON,โสดตั้งแต่เกิด,เพื่อนเก่า,กลับมาพบกันอีกครั้ง,เมะเจ้าเล่ห์,เมะฮอต,เมะเจ้าแผนการ,เมะไฮโซ,เมะรักจริง,เคะจน,เคะคนซึน,เคะหนี,เรื่องสั้น',
    updatedAt: 1637254800000,
    creators: 'Ma jeung ji',
  },
  {
    id: 290,
    alias: 'please_candy',
    title: 'Please, Candy!',
    isAdult: false,
    isComplete: false,
    orderNo: 40,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/please_can/1684395628487.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/please_can/1684395628760.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: false,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 39439,
    tag: 'BL,กลับมาพบกันอีกครั้ง,มนุษย์เงินเดือน,เมะเจ้าแผนการ,เมะแอบรัก,เคะแอบรัก,เคะใสซื่อ,ออฟฟิต,รุ่นพี่รุ่นน้อง,รักในที่ทำงาน,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1685638800000,
    creators: 'NOD',
  },
  {
    id: 305,
    alias: 'weakness',
    title: 'WEAKNESS',
    isAdult: false,
    isComplete: false,
    orderNo: 42,
    thumbnails: [
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/her_weakne/1686102561920.webp',
        type: 'SQUARE',
      },
      {
        imagePath: 'https://image.balcony.studio/th/co_thumbnail/her_weakne/1686102562074.webp',
        type: 'MAIN',
      },
    ],
    badge: {
      newest: true,
      adult: false,
      scheduled: false,
      up: true,
      completed: true,
      recommended: false,
      discount: 0,
      free: 1,
      freetime: false,
    },
    viewCount: 1090,
    tag: 'GL,ดราม่า,สายดาร์ค,นางเอกไฮโซ,นางเอกเพอร์เฟ็ค,นางเอกแซ่บ,นางเอกจน,นางเอกร้าย,OnlyBOOMTOON,เรื่องสั้น,อะพาร์ตเมนต์คลั่งรัก',
    updatedAt: 1686848400000,
    creators: 'BBTAN',
  },
];
